spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

cache:
  dataObjects: 1000
  maxCacheSize: 200